apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: hiraku-ai
  name: hiraku-ai-pvc
  namespace: hiraku-ai
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi